### ISSUE TITLE
oauth2_client_token_settings failed to set the token valid time

### ISSUE THREAD

**Issue by meimosor** [Basit-Mahmood/spring-authorization-server-spring-boot-3#3]
### oauth2_client_token_settings：
![image](https://user-images.githubusercontent.com/31975932/210463563-c4c820b1-99ce-457a-98f4-288dc1d3384f.png)
### expect：
The expiration time for getting tokens should be 3600S
### actual：
![image](https://user-images.githubusercontent.com/31975932/210463656-1a19e471-da06-4cec-b43d-6b0bc4e63de7.png)

**Comment by Basit-Mahmood** [comment]
@meimosor
Is this ID token ? For ID token it always sets time to 30 min when generates the token. May be in next version of Authorization server it will be fix.

![image](https://user-images.githubusercontent.com/47849735/212564580-96507128-f8c2-45ef-adb5-6fdc3463819f.png)

But if it's a normal token then it is setting time correctly. I generated the token with 60 min client_token_setting. And in the database it can be seen it is setting expiry time of 1 hour 

![image](https://user-images.githubusercontent.com/47849735/212564675-47df943e-53fd-46de-b3f5-bf4daea5cd1a.png)

Thanks & Regards
Basit Mahmood Ahmed

**Comment by meimosor** [comment]
> @meimosor Is this ID token ? For ID token it always sets time to 30 min when generates the token. May be in next version of Authorization server it will be fix.
> 
> ![image](https://user-images.githubusercontent.com/47849735/212564580-96507128-f8c2-45ef-adb5-6fdc3463819f.png)
> 
> But if it's a normal token then it is setting time correctly. I generated the token with 60 min client_token_setting. And in the database it can be seen it is setting expiry time of 1 hour
> 
> ![image](https://user-images.githubusercontent.com/47849735/212564675-47df943e-53fd-46de-b3f5-bf4daea5cd1a.png)
> 
> Thanks & Regards Basit Mahmood Ahmed

Thank you for your reply. It has been very helpful to me!

**Comment by meimosor** [comment]
![image](https://user-images.githubusercontent.com/31975932/235124381-0e8e83e6-9f75-4475-ab11-1b5c25d50923.png)
![image](https://user-images.githubusercontent.com/31975932/235124844-9f686d9f-28f5-4365-b506-ccc88c651f32.png)

it seems doesn't work. token setting 50 min, but the access_token expired time is also 30min.
